### ISSUE TITLE
Wrong sourcetype being set within [monitor:///opt/nifi/logs/nifi-bootstrap*.log]

### ISSUE THREAD

**Issue by barrettnet** [kudawdev/nifi-monitoring-splunk#11]
I suspect that the [monitor:///opt/nifi/logs/nifi-bootstrap*.log] stanza within the TA should be setting the sourcetype to nifi:log:bootstrap and not nifi:log:app as it is currently doing.

**Comment by idglabs** [comment]
Hi Chris,
sorry to disturb you but in which file  if fnd this error?
thankyou

**Comment by barrettnet** [comment]
https://github.com/kudawdev/nifi-monitoring-splunk/blob/main/nifi_TA_monitoring/default/inputs.conf

**Comment by avasquezkudaw** [comment]
Hello Chris,

You're right. In the next few days we will generate a new version with this and other corrections to the app, and we will close this issue when it is resolved.

Greetings and thanks for using NIFI Monitoring for Splunk

**Comment by barrettnet** [comment]
1.0.2 is still (as of 23 August) the latest version available on SplunkBase.  Could you please submit 1.1.0 (or later) to SplunkBase.

**Comment by avasquezkudaw** [comment]
Hello, I will fix it in 1.1.0.
When it is published, we will close this issue.
Regards.
