### ISSUE TITLE
Total Queued Data  empty data

### ISSUE THREAD

**Issue by idglabs** [kudawdev/nifi-monitoring-splunk#12]
the panel "Total Queued Data " is not showing any information 
| table queued

under the  nifi instance details. dashboard
(not sure if that it's only my problem)

thanks

**Comment by avasquezkudaw** [comment]
Hi,

I'm testing the app and Total Queued Data show results for me:

![image](https://user-images.githubusercontent.com/50120087/180857648-039da6bd-47a4-4c4e-89d6-f9b894fc8907.png)

Please, run this query an check if json object show this indicator

index=nifi sourcetype="nifi:api:flow_status" host=*

![image](https://user-images.githubusercontent.com/50120087/180858091-b8397069-2e46-4baf-8785-ec8b0eafc13e.png)

**Comment by idglabs** [comment]
Thank you for confirmation and support

I have as well data  for " queued"
