### ISSUE TITLE
Instances Panel returns 404 Not Found

### ISSUE THREAD

**Issue by jowayn** [kudawdev/nifi-monitoring-splunk#14]
The NiFi instances panel under Configuration > Lookups > NiFi Instances throws a 404 error. Will need the instances panel to correctly configure a NiFi instance to use with the Splunk app. Do let me know if there are any updates on this! Thanks!

**Comment by idglabs** [comment]
Hi jowayn,

I have that error in the past on
What splunk version are you using?
do you have the access to Lookups menu in splunk  because can be  problem related to permissions  

thanks

**Comment by jowayn** [comment]
Hi, I am using Splunk version 9.0.0. Yes, I do have access to the Lookups Menu. Is the Instances panel working on your end? What suggestions might you have to fix this issue? Thanks!

**Comment by idglabs** [comment]
yes menu is working find on my instance where I'm admin with full access  splunk 8.1.1

if you don;t have access to lookups menu in splunk (Settings--> Lookups)  fast solution is to import a lookups in csv file, i did this and was working but let's see what @kudawdev suggest.

**Comment by jowayn** [comment]
Could you elaborate on what you mean by a lookups csv? What should this csv contain?
I do have access to Settings --> Lookups as admin. Have tried to downgrade to Splunk 8.1.1 as well, but still facing the same issue of a 404 error when accessing the Lookups > NiFi Instances panel. Thank you so much for your help!

**Comment by jowayn** [comment]
Update: Have found the fix for the problem. It is simply a matter of installing the additional 2 Splunk apps 
([Lookup File Editor](https://splunkbase.splunk.com/app/1724/)
[Status Indicator - Custom Visualization](https://splunkbase.splunk.com/app/3119/)

**Comment by idglabs** [comment]
yes correct  related to app "Lookup File Editor" , in my scenario for security policy  this app is denied, so I'm uploaded CSV .

Thanks for details

**Comment by avasquezkudaw** [comment]
Hi,

We add the pre-requisites in the documentation:

![image](https://user-images.githubusercontent.com/50120087/180866640-c960be9d-a1c0-43bf-8855-f0a60462cce0.png)

Thanks.

**Comment by avasquezkudaw** [comment]
Hello, it's related to pre-requisites. Regards
