### ISSUE TITLE
Total Task Duration (Seconds)  Empty

### ISSUE THREAD

**Issue by idglabs** [kudawdev/nifi-monitoring-splunk#16]
Hi all,

Under the instance details  page

nifi_instance_details
the panel  Total Task Duration (Seconds)

with:
- Max_TotalTaskDurationSeconds
- Avg_TotalTaskDurationSeconds

are always empty ...I'm wondering if I need to enable some logs or some flags in order to provide information to this panel

and my dummy question what exactly this panel calculate?

Thank you

**Comment by avasquezkudaw** [comment]
Hi,

The data from my nifi show 0 in this field.

Run index=* sourcetype="nifi:reporting:task" query and show

![image](https://user-images.githubusercontent.com/50120087/180868909-60ce39ee-a122-4ebf-a405-865fafd51847.png)

**Comment by idglabs** [comment]
thanks again for your support

TotalTaskDuration it;s in the search  as well, but on the panel is always not shown the value,  maybe because is very small value
![totalduration](https://user-images.githubusercontent.com/1655007/180986984-5a798c92-7f7a-475d-8eb7-7f630719d9a3.jpg)
