### ISSUE TITLE
image missing in docs 

### ISSUE THREAD

**Issue by idglabs** [kudawdev/nifi-monitoring-splunk#18]
Hi all,

All images in the page 
https://github.com/kudawdev/nifi-monitoring-splunk/blob/main/docs/installation.md
https://github.com/kudawdev/nifi-monitoring-splunk/blob/main/docs/installation.es.md
are missing 404

thanks

**Comment by idglabs** [comment]
as well here
https://github.com/kudawdev/nifi-monitoring-splunk/blob/main/docs/index.md

and I think a typo error here in page
https://github.com/kudawdev/nifi-monitoring-splunk/blob/main/docs/references.md

nifi:reporting:bulleting      letter g on the end >  nifi:reporting:bulletin

**Comment by avasquezkudaw** [comment]
Yes, i'm checking it, but i have problem because when i change the path, the documentation image are missing.
I will fix the name of the nifi:reporting:bulletin
