### ISSUE TITLE
Nifi Monitor Overview 1.1.0    field to choose /select cluster missing

### ISSUE THREAD

**Issue by idglabs** [kudawdev/nifi-monitoring-splunk#24]
nifi_overview page ,  seems it's missing the first block to select  cluster (only if you want to add this new feature) ,

like per image,
![nifi_overview](https://user-images.githubusercontent.com/1655007/183386553-0ec7c5f6-9ad5-43e2-b140-e514b9240907.gif)

**Comment by avasquezkudaw** [comment]
Hello, tell me if the problem persist in your instance to check it. Regards.

**Comment by idglabs** [comment]
all solved .thank you
